# Base tier: Core CLI tools needed for a functional dev environment
brew "chezmoi"
brew "git"
brew "fzf"
brew "bat"
brew "btop"
brew "eza"
brew "fd"
brew "ripgrep"
brew "zoxide"
brew "starship"
brew "neovim"
brew "curl"
brew "wget"
brew "jq"
brew "grep"
brew "atuin"
brew "git-delta"
