# Nice-to-have tier: Useful but not critical tools and apps
brew "aria2"
brew "ffmpeg"
brew "ffmpegthumbnailer"
brew "fish"
brew "ghostscript"
brew "jj"
brew "llvm"
brew "mermaid-cli"
brew "pandoc"
brew "poppler"
brew "sevenzip"
brew "syncthing", restart_service: :changed
brew "yt-dlp"
cask "discord"
cask "docker-desktop"
cask "firefox@developer-edition"
cask "iina"
cask "itsycal"
cask "keka"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "telegram"
